### ISSUE TITLE
Missing app headers?

### ISSUE THREAD

**Issue by tmm1** [lechium/tvOS135Headers#1]
Compare the files in older header repos vs this one:

https://github.com/lechium/tvOS130Headers/tree/master/Applications/AppleTV

https://github.com/lechium/tvOS135Headers/tree/master/Applications/AppleTV

Only protocols/delegate headers seem to be present now.

**Comment by lechium** [comment]
good catch, i will investigate this asap

**Comment by lechium** [comment]
fixed in latest commit, sorry about that!
